// <auto-generated />
namespace ArooshyStore.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Added_Column_IsExpiredBarcodeinTblProductAttributeDetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_Column_IsExpiredBarcodeinTblProductAttributeDetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202410291018130_Added_Column_IsExpired&BarcodeinTblProduct&AttributeDetail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
