// <auto-generated />
namespace ArooshyStore.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Dropped_Column_Barcode_tblProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dropped_Column_Barcode_tblProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202412291043014_Dropped_Column_Barcode_tblProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
