// <auto-generated />
namespace ArooshyStore.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Added_TableColumn_tblDeliveryInfoColumnProductDescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_TableColumn_tblDeliveryInfoColumnProductDescription));
        
        string IMigrationMetadata.Id
        {
            get { return "202409241312200_Added_Table&Column_tblDeliveryInfo&ColumnProductDescription"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
