// <auto-generated />
namespace ArooshyStore.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Dropped_Table_tblProductAttributeDetailBarcode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Dropped_Table_tblProductAttributeDetailBarcode));
        
        string IMigrationMetadata.Id
        {
            get { return "202501011211275_Dropped_Table_tblProductAttributeDetailBarcode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
